name: bci2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - alabaster=0.7.12
  - apr=1.6.3
  - argh=0.26.2
  - asn1crypto=1.3.0
  - astroid=2.3.3
  - atomicwrites=1.3.0
  - attrs=19.3.0
  - autopep8=1.4.4
  - babel=2.8.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - boost-cpp=1.70.0
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - catkin_pkg=0.4.16
  - certifi=2019.11.28
  - cffi=1.14.0
  - chardet=3.0.4
  - cloudpickle=1.3.0
  - cmake=3.14.0
  - console_bridge=0.4.4
  - cryptography=2.8
  - cycler=0.10.0
  - dbus=1.13.12
  - decorator=4.4.2
  - defusedxml=0.6.0
  - diff-match-patch=20181111
  - distro=1.4.0
  - docutils=0.16
  - empy=3.3.4
  - entrypoints=0.3
  - expat=2.2.6
  - flake8=3.7.9
  - fontconfig=2.13.0
  - freetype=2.9.1
  - future=0.18.2
  - glib=2.63.1
  - gmock=1.10.0
  - gmp=6.1.2
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - gtest=1.10.0
  - hyperopt=0.2.2
  - icu=58.2
  - imagesize=1.2.0
  - importlib_metadata=1.5.0
  - intel-openmp=2020.0
  - intervaltree=3.0.2
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - isort=4.3.21
  - jedi=0.14.1
  - jeepney=0.4.3
  - jinja2=2.11.1
  - joblib=0.14.1
  - jpeg=9c
  - jsonschema=3.2.0
  - jupyter_client=6.0.0
  - jupyter_core=4.6.1
  - keyring=21.1.0
  - kivy=1.11.1
  - kiwisolver=1.1.0
  - krb5=1.17.1
  - lazy-object-proxy=1.4.3
  - ld_impl_linux-64=2.33.1
  - libapr=1.6.5
  - libaprutil=1.6.1
  - libcurl=7.69.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - libpng=1.6.37
  - libsodium=1.0.16
  - libspatialindex=1.9.3
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - log4cxx=0.10.0
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.2
  - netifaces=0.10.9
  - networkx=2.4
  - nose=1.3.7
  - notebook=6.0.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - numpydoc=0.9.2
  - olefile=0.46
  - openssl=1.1.1e
  - packaging=20.3
  - pandas=1.0.2
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.2
  - pathtools=0.1.2
  - patsy=0.5.1
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - pkg-config=0.29.2
  - pluggy=0.13.1
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.3
  - psutil=5.7.0
  - ptyprocess=0.6.0
  - pycodestyle=2.5.0
  - pycparser=2.20
  - pydocstyle=4.0.1
  - pyflakes=2.1.1
  - pygments=2.6.1
  - pylint=2.4.4
  - pymongo=3.9.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pyqtgraph=0.10.0
  - pyrsistent=0.15.7
  - pyserial=3.4
  - pysocks=1.7.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.3.4
  - python-language-server=0.31.8
  - python_abi=3.7
  - pytz=2019.3
  - pyxdg=0.26
  - pyyaml=5.3
  - pyzmq=18.1.1
  - qdarkstyle=2.8
  - qt=5.9.7
  - qtawesome=0.7.0
  - qtconsole=4.7.1
  - qtpy=1.9.0
  - readline=7.0
  - requests=2.23.0
  - rhash=1.3.8
  - rope=0.16.0
  - ros-catkin=0.7.17
  - ros-conda-base=0.0.1
  - ros-conda-mutex=1.0
  - ros-cpp-common=0.6.12
  - ros-environment=1.2.1
  - ros-gencpp=0.6.2
  - ros-geneus=2.2.6
  - ros-genlisp=0.4.16
  - ros-genmsg=0.5.12
  - ros-gennodejs=2.0.1
  - ros-genpy=0.6.8
  - ros-message-generation=0.4.0
  - ros-message-runtime=0.4.12
  - ros-rosbuild=1.14.6
  - ros-rosconsole=1.13.10
  - ros-roscpp=1.14.3
  - ros-roscpp-serialization=0.6.12
  - ros-roscpp-traits=0.6.12
  - ros-rosgraph=1.14.3
  - ros-rosgraph-msgs=1.11.2
  - ros-roslib=1.14.6
  - ros-rospack=2.5.3
  - ros-rospy=1.14.3
  - ros-rostime=0.6.12
  - ros-std-msgs=0.5.12
  - ros-xmlrpcpp=1.14.3
  - rosdep=0.18.0
  - rosdistro=0.8.0
  - rospkg=1.2.3
  - rtree=0.9.3
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - sdl2=2.0.9
  - sdl2_image=2.0.5
  - sdl2_mixer=2.0.4
  - sdl2_ttf=2.0.15
  - seaborn=0.10.0
  - secretstorage=3.1.2
  - send2trash=1.5.0
  - setuptools=46.0.0
  - sip=4.19.8
  - six=1.14.0
  - smpeg2=2.0.0
  - snowballstemmer=2.0.0
  - sortedcontainers=2.1.0
  - sphinx=2.4.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - spyder=4.0.1
  - spyder-kernels=1.8.1
  - sqlite=3.31.1
  - statsmodels=0.11.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tinyxml2=7.1.0
  - tk=8.6.8
  - tornado=6.0.4
  - tqdm=4.43.0
  - traitlets=4.3.3
  - ujson=1.35
  - watchdog=0.10.2
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.34.2
  - wrapt=1.12.1
  - wurlitzer=2.0.0
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.6.7
  - xorg-libxext=1.3.4
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - yapf=0.28.0
  - zeromq=4.3.1
  - zipp=2.2.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - bar==0.2.1
    - bitstring==3.1.6
    - bluepy==1.3.0
    - buildozer==1.0
    - colorize==1.1.0
    - cvxopt==1.2.3
    - cython==0.29.14
    - django==2.2.7
    - idna==2.8
    - image==1.5.27
    - kivy-garden==0.1.4
    - libsvm==3.23.0.3
    - mne==0.19.dev0
    - mouseinfo==0.1.2
    - openbci-python==1.0.2
    - osqp==0.6.1
    - overmind==1.1
    - prml==0.0.1
    - pyautogui==0.9.48
    - pygame==1.9.6
    - pygetwindow==0.0.8
    - pylsl==1.10.5
    - pymsgbox==1.0.7
    - pyopenbci==0.13
    - pyperclip==1.7.0
    - pyrect==0.1.4
    - pyscreeze==0.1.26
    - python-osc==1.7.4
    - python3-xlib==0.15
    - pytweening==1.0.3
    - qpsolvers==1.0.7
    - quadprog==0.1.7
    - sh==1.12.14
    - sklearn==0.0
    - sqlparse==0.3.0
    - tf==1.0.0
    - urllib3==1.25.3
    - virtualenv==16.7.9
    - xmltodict==0.12.0
    - yapsy==1.12.2

